import { withIronSessionSsr } from "iron-session/next";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { FormBuilder } from "../../../components/FormBuilder";
import { sessionOptions } from "../../../helpers/session";
import useSessionStorage from "../../../hooks/useSessionStorage";

const Home: NextPage = () => {
  const isLogged = useSessionStorage("isLogged");
  useEffect(() => {
    if (!isLogged) {
      sessionStorage.setItem("isLogged", "true");
    }
  }, [isLogged])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FormBuilder />
    </>
  );
};

export const getServerSideProps = withIronSessionSsr(async function getServerSideProps({
  req,
  res,
}) {
  const isLogged = req.session.isLogged;

  if (isLogged === undefined || isLogged === false) {
    res.setHeader("location", "/login");
    res.statusCode = 302;
    res.end();
  }

  return {
    props: {

    }
  };
},
  sessionOptions);

export default Home;
