import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Router from 'next/router'

const Home: NextPage = () => {
    const [password, setPassword] = useState("");
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="min-h-1/2 bg-white  border border-gray-400 rounded-2xl">
                <div className="sm:mx-24 md:mx-34 lg:mx-56 mx-auto  flex items-center space-y-4 py-16 font-semibold text-gray-500 flex-col">
                    <h1 className="text-black text-2xl">
                        Connexion panel admin
                    </h1>
                    <input
                        className="w-full p-2 bg-white rounded-md border border-gray-300"
                        placeholder="Mot de passe*"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        type="password" name="correo" id="" />
                    <button
                        onClick={() => {
                            fetch("/api/login", {
                                method: "POST",
                                body: JSON.stringify({
                                    password
                                })
                            }).then(response => {
                                if (response.status === 200) {
                                    sessionStorage.setItem("isLogged", "true");
                                    Router.push("/admin");
                                }
                            })
                        }}
                        className="w-full p-2 bg-gray-50 rounded-full font-bold text-gray-900 border border-gray-700">
                        Se connecter
                    </button>

                </div>
            </div>
        </div>
    );
};

export default Home;
